export interface Murakkab {
  number: number;
  englishName: string;
  urduName: string;
  remedyName: string;
}

export const MURAKKABAT_LIST: Murakkab[] = [
  { number: 1, englishName: "Headache", urduName: "سر درد", remedyName: "HHC Compound No. 1 - Headache (سر درد)" },
  { number: 2, englishName: "Migraine", urduName: "درد شقیقہ", remedyName: "HHC Compound No. 2 - Migraine (درد شقیقہ)" },
  { number: 3, englishName: "Ophthalima", urduName: "آنکھ کی خرابی", remedyName: "HHC Compound No. 3 - Ophthalima (آنکھ کی خرابی)" },
  { number: 4, englishName: "Coryza", urduName: "نزلہ زکام", remedyName: "HHC Compound No. 4 - Coryza (نزلہ زکام)" },
  { number: 5, englishName: "Dry Cough", urduName: "خشک کھانسی", remedyName: "HHC Compound No. 5 - Dry Cough (خشک کھانسی)" },
  { number: 6, englishName: "Whooping Cough", urduName: "کالی کھانسی", remedyName: "HHC Compound No. 6 - Whooping Cough (کالی کھانسی)" },
  { number: 7, englishName: "Asthma", urduName: "دمہ", remedyName: "HHC Compound No. 7 - Asthma (دمہ)" },
  { number: 8, englishName: "Pharyngitis", urduName: "گلا خراب", remedyName: "HHC Compound No. 8 - Pharyngitis (گلا خراب)" },
  { number: 9, englishName: "Tonsils", urduName: "ٹانسلز", remedyName: "HHC Compound No. 9 - Tonsils (ٹانسلز)" },
  { number: 10, englishName: "Indigestion", urduName: "پیٹ میں خرابی", remedyName: "HHC Compound No. 10 - Indigestion (پیٹ میں خرابی)" },
  { number: 11, englishName: "Worms", urduName: "پیٹ کے کیڑے", remedyName: "HHC Compound No. 11 - Worms (پیٹ کے کیڑے)" },
  { number: 12, englishName: "Diarrhoea", urduName: "اسہال", remedyName: "HHC Compound No. 12 - Diarrhoea (اسہال)" },
  { number: 13, englishName: "Cholera", urduName: "ہیضہ", remedyName: "HHC Compound No. 13 - Cholera (ہیضہ)" },
  { number: 14, englishName: "Dysentry", urduName: "پیچش", remedyName: "HHC Compound No. 14 - Dysentry (پیچش)" },
  { number: 15, englishName: "Piles", urduName: "بواسیر", remedyName: "HHC Compound No. 15 - Piles (بواسیر)" },
  { number: 16, englishName: "Low B. P", urduName: "لو بلڈ پریشر", remedyName: "HHC Compound No. 16 - Low B. P (لو بلڈ پریشر)" },
  { number: 17, englishName: "High B.P", urduName: "ہائی بلڈ پریشر", remedyName: "HHC Compound No. 17 - High B.P (ہائی بلڈ پریشر)" },
  { number: 18, englishName: "Angina", urduName: "انجائنا", remedyName: "HHC Compound No. 18 - Angina (انجائنا)" },
  { number: 19, englishName: "Epilepsy", urduName: "مرگی کے دورے", remedyName: "HHC Compound No. 19 - Epilepsy (مرگی کے دورے)" },
  { number: 20, englishName: "E Sebont (Bone Joining)", urduName: "ہڈی جوڑنا", remedyName: "HHC Compound No. 20 - E Sebont (ہڈی جوڑنا)" },
  { number: 21, englishName: "Influenza / Flu", urduName: "فلو، انفلوئنزا، نمونیہ", remedyName: "HHC Compound No. 21 - Influenza (فلو، انفلوئنزا، نمونیہ)" },
  { number: 22, englishName: "Malaria", urduName: "ملیریا", remedyName: "HHC Compound No. 22 - Malaria (ملیریا)" },
  { number: 23, englishName: "Typhoid", urduName: "ٹائیفائیڈ", remedyName: "HHC Compound No. 23 - Typhoid (ٹائیفائیڈ)" },
  { number: 24, englishName: "Meningitis", urduName: "گردن توڑ بخار", remedyName: "HHC Compound No. 24 - Meningitis (گردن توڑ بخار)" },
  { number: 25, englishName: "Measles", urduName: "خسرہ", remedyName: "HHC Compound No. 25 - Measles (خسرہ)" },
  { number: 26, englishName: "Paralysis", urduName: "فالج", remedyName: "HHC Compound No. 26 - Paralysis (فالج)" },
  { number: 27, englishName: "Tremor", urduName: "رعشہ", remedyName: "HHC Compound No. 27 - Tremor (رعشہ)" },
  { number: 28, englishName: "Stammering", urduName: "لکنت", remedyName: "HHC Compound No. 28 - Stammering (لکنت)" },
  { number: 29, englishName: "Short Hight", urduName: "چھوٹا قد", remedyName: "HHC Compound No. 29 - Short Hight (چھوٹا قد)" },
  { number: 30, englishName: "Enuresis", urduName: "بول بستری", remedyName: "HHC Compound No. 30 - Enuresis (بول بستری)" },
  { number: 31, englishName: "Diabetes", urduName: "شوگر", remedyName: "HHC Compound No. 31 - Diabetes (شوگر)" },
  { number: 32, englishName: "Kidney Pain", urduName: "درد گردہ", remedyName: "HHC Compound No. 32 - Kidney Pain (درد گردہ)" },
  { number: 33, englishName: "Gall Stone", urduName: "پتے میں پتھری", remedyName: "HHC Compound No. 33 - Gall Stone (پتے میں پتھری)" },
  { number: 34, englishName: "Travel Sickness", urduName: "سفر میں متلی", remedyName: "HHC Compound No. 34 - Travel Sickness (سفر میں متلی)" },
  { number: 35, englishName: "Leucorrhoea", urduName: "لیکوریا", remedyName: "HHC Compound No. 35 - Leucorrhoea (لیکوریا)" },
  { number: 36, englishName: "Acne", urduName: "چہرے کے کیل", remedyName: "HHC Compound No. 36 - Acne (چہرے کے کیل)" },
  { number: 37, englishName: "Warts", urduName: "موہکے", remedyName: "HHC Compound No. 37 - Warts (موہکے)" },
  { number: 38, englishName: "Eczema", urduName: "چنبل", remedyName: "HHC Compound No. 38 - Eczema (چنبل)" },
  { number: 39, englishName: "Tumor", urduName: "رسولی، ٹیومر", remedyName: "HHC Compound No. 39 - Tumor (رسولی، ٹیومر)" },
  { number: 40, englishName: "Aphthar", urduName: "منہ کے چھالے", remedyName: "HHC Compound No. 40 - Aphthar (منہ کے چھالے)" },
  { number: 41, englishName: "Toothache", urduName: "دانت کا درد", remedyName: "HHC Compound No. 41 - Toothache (دانت کا درد)" },
  { number: 42, englishName: "Ear.Ache", urduName: "کان درد", remedyName: "HHC Compound No. 42 - Ear.Ache (کان درد)" },
  { number: 43, englishName: "Back.Ache", urduName: "کمر درد", remedyName: "HHC Compound No. 43 - Back.Ache (کمر درد)" },
  { number: 44, englishName: "Sciatics", urduName: "عرق النساء، لنگڑی کا درد", remedyName: "HHC Compound No. 44 - Sciatics (عرق النساء، لنگڑی کا درد)" },
  { number: 45, englishName: "Arthritis", urduName: "جوڑوں کا درد", remedyName: "HHC Compound No. 45 - Arthritis (جوڑوں کا درد)" },
  { number: 46, englishName: "Sun.Stroke", urduName: "لو لگنا", remedyName: "HHC Compound No. 46 - Sun.Stroke (لو لگنا)" },
  { number: 47, englishName: "Delirium", urduName: "ہذیان", remedyName: "HHC Compound No. 47 - Delirium (ہذیان)" },
  { number: 48, englishName: "General Tonic", urduName: "اعصاب کا ٹانک", remedyName: "HHC Compound No. 48 - General Tonic (اعصاب کا ٹانک)" },
  { number: 49, englishName: "Prostate Gland", urduName: "پراسٹیٹ گلینڈز", remedyName: "HHC Compound No. 49 - Prostate Gland (پراسٹیٹ گلینڈز)" },
  { number: 50, englishName: "Bites", urduName: "سانپ، بچھو کا کاٹنا", remedyName: "HHC Compound No. 50 - Bites (سانپ، بچھو کا کاٹنا)" }
];
